version: "3.8"
services:
  iwbonline:
    build:
      context: "${BUILD_CONTEXT}"
      dockerfile: "${BUILD_CONTEXT}/docker/windows/dockerfile"
      args:
        BASE_IMG: "${BASE_IMG}"
    image: "iwbonline:${TAG}"
    env_file:
      - .env
    container_name: iwbonline
    hostname: iwbonline
    ports:
      - "1096:1096"
    volumes:
      - type: bind
        source: C:/opt/me/iwbonline
        target: /opt/me/iwbonline
    command: >
      bash -c "
      node src/app.js;
      tail -f /dev/null"